package org.sid.reverse;
// Generated 30 avr. 2019 01:04:31 by Hibernate Tools 3.6.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Administrateur generated by hbm2java
 */
@Entity
@Table(name = "administrateur", schema = "public")
public class Administrateur implements java.io.Serializable {
	

	private int idUtilisateur;
	private Utilisateur utilisateur;
	private String administrateur;

	public Administrateur() {
	}

	public Administrateur(Utilisateur utilisateur, String administrateur) {
		this.utilisateur = utilisateur;
		this.administrateur = administrateur;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "utilisateur"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "id_utilisateur", unique = true, nullable = false)
	public int getIdUtilisateur() {
		return this.idUtilisateur;
	}

	public void setIdUtilisateur(int idUtilisateur) {
		this.idUtilisateur = idUtilisateur;
	}

	@OneToOne(fetch = FetchType.EAGER)
	@JsonIgnoreProperties("administrateur")
	@PrimaryKeyJoinColumn
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	@Column(name = "administrateur", nullable = false, length = 254)
	public String getAdministrateur() {
		return this.administrateur;
	}

	public void setAdministrateur(String administrateur) {
		this.administrateur = administrateur;
	}

}
