package org.sid.reverse;
// Generated 30 avr. 2019 01:04:31 by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Artisan generated by hbm2java
 */
@Entity
@Table(name = "artisan", schema = "public")
@JsonIgnoreProperties({"hibernateLazyInitializer","handler"})
public class Artisan implements java.io.Serializable {

	private int idUtilisateur;
	//private Villageartisanal villageartisanal;
	private Utilisateur utilisateur;
	private Set<Boutique> boutiques = new HashSet(0);
	private Set<Article> articles = new HashSet(0);

	public Artisan() {
	}

	public Artisan(Villageartisanal villageartisanal, Utilisateur utilisateur) {
		//this.villageartisanal = villageartisanal;
		this.utilisateur = utilisateur;
		
	}

	public Artisan(Villageartisanal villageartisanal, Utilisateur utilisateur,  Set<Boutique> boutiques,
			Set<Article> articles) {
		//this.villageartisanal = villageartisanal;
		this.utilisateur = utilisateur;
		this.boutiques = boutiques;
		this.articles = articles;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "utilisateur"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "id_utilisateur", unique = true)
	public int getIdUtilisateur() {
		return this.idUtilisateur;
	}

	public void setIdUtilisateur(int idUtilisateur) {
		this.idUtilisateur = idUtilisateur;
	}

/*	@ManyToOne(fetch = FetchType.EAGER)
	@JsonIgnoreProperties("artisans")
	@JoinColumn(name = "id_villageartisanal", nullable = false)
	public Villageartisanal getVillageartisanal() {
		return this.villageartisanal;
	}

	public void setVillageartisanal(Villageartisanal villageartisanal) {
		this.villageartisanal = villageartisanal;
	}*/

	@OneToOne(fetch = FetchType.EAGER)
	@JsonIgnoreProperties("artisan")
	@PrimaryKeyJoinColumn
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}


	@OneToMany(fetch = FetchType.EAGER, mappedBy = "artisan")
	@JsonIgnoreProperties("artisan")
	public Set<Boutique> getBoutiques() {
		return this.boutiques;
	}

	public void setBoutiques(Set<Boutique> boutiques) {
		this.boutiques = boutiques;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "artisan")
	@JsonIgnoreProperties("artisan")
	public Set<Article> getArticles() {
		return this.articles;
	}

	public void setArticles(Set<Article> articles) {
		this.articles = articles;
	}

}
