package org.sid.reverse;
// Generated 30 avr. 2019 01:04:31 by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Chambremetier generated by hbm2java
 */
@Entity
@Table(name = "chambremetier", schema = "public")
public class Chambremetier implements java.io.Serializable {

	private int idChambremetier;
	private Departement departement;
	private String nomChambremetier;
	private String commune;
	private Set<Superviseur> superviseurs = new HashSet(0);
	private Set<Villageartisanal> villageartisanals = new HashSet(0);

	public Chambremetier() {
	}

	public Chambremetier(int idChambremetier, Departement departement) {
		this.idChambremetier = idChambremetier;
		this.departement = departement;
	}

	public Chambremetier(int idChambremetier, Departement departement, String nomChambremetier, String commune,
			Set<Superviseur> superviseurs, Set<Villageartisanal> villageartisanals) {
		this.idChambremetier = idChambremetier;
		this.departement = departement;
		this.nomChambremetier = nomChambremetier;
		this.commune = commune;
		this.superviseurs = superviseurs;
		this.villageartisanals = villageartisanals;
	}

	@Id

	@Column(name = "id_chambremetier", unique = true, nullable = false)
	public int getIdChambremetier() {
		return this.idChambremetier;
	}

	public void setIdChambremetier(int idChambremetier) {
		this.idChambremetier = idChambremetier;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_departement", nullable = false)
	@JsonIgnoreProperties("chambremetiers")
	public Departement getDepartement() {
		return this.departement;
	}

	public void setDepartement(Departement departement) {
		this.departement = departement;
	}

	@Column(name = "nom_chambremetier", length = 254)
	public String getNomChambremetier() {
		return this.nomChambremetier;
	}

	public void setNomChambremetier(String nomChambremetier) {
		this.nomChambremetier = nomChambremetier;
	}

	@Column(name = "commune", length = 254)
	public String getCommune() {
		return this.commune;
	}

	public void setCommune(String commune) {
		this.commune = commune;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "chambremetier")
	@JsonIgnoreProperties("chambremetier")
	public Set<Superviseur> getSuperviseurs() {
		return this.superviseurs;
	}

	public void setSuperviseurs(Set<Superviseur> superviseurs) {
		this.superviseurs = superviseurs;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "chambremetier")
	@JsonIgnoreProperties("chambremetier")
	public Set<Villageartisanal> getVillageartisanals() {
		return this.villageartisanals;
	}

	public void setVillageartisanals(Set<Villageartisanal> villageartisanals) {
		this.villageartisanals = villageartisanals;
	}

}
