package org.sid.reverse;
// Generated 30 avr. 2019 01:04:31 by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Departement generated by hbm2java
 */
@Entity
@Table(name = "departement", schema = "public")
public class Departement implements java.io.Serializable {

	private int idDepartement;
	private Region region;
	private String nomDepartement;
	private Set<Chambremetier> chambremetiers = new HashSet(0);

	public Departement() {
	}

	public Departement(int idDepartement, Region region) {
		this.idDepartement = idDepartement;
		this.region = region;
	}

	public Departement(int idDepartement, Region region, String nomDepartement, Set<Chambremetier> chambremetiers) {
		this.idDepartement = idDepartement;
		this.region = region;
		this.nomDepartement = nomDepartement;
		this.chambremetiers = chambremetiers;
	}

	@Id

	@Column(name = "id_departement", unique = true, nullable = false)
	public int getIdDepartement() {
		return this.idDepartement;
	}

	public void setIdDepartement(int idDepartement) {
		this.idDepartement = idDepartement;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JsonIgnoreProperties("departements")
	@JoinColumn(name = "id_region", nullable = false)
	public Region getRegion() {
		return this.region;
	}

	public void setRegion(Region region) {
		this.region = region;
	}

	@Column(name = "nom_departement", length = 254)
	public String getNomDepartement() {
		return this.nomDepartement;
	}

	public void setNomDepartement(String nomDepartement) {
		this.nomDepartement = nomDepartement;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "departement")
	@JsonIgnoreProperties("departement")
	public Set<Chambremetier> getChambremetiers() {
		return this.chambremetiers;
	}

	public void setChambremetiers(Set<Chambremetier> chambremetiers) {
		this.chambremetiers = chambremetiers;
	}

}
