package org.sid.reverse;
// Generated 30 avr. 2019 01:04:31 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Facture generated by hbm2java
 */
@Entity
@Table(name = "facture", schema = "public", uniqueConstraints = { @UniqueConstraint(columnNames = "id_paiement"),
		@UniqueConstraint(columnNames = "numcommande"),
		@UniqueConstraint(columnNames = { "numcommande", "id_paiement" }) })
public class Facture implements java.io.Serializable {

	private int idfacture;
	private Commande commande;
	private Paiement paiement;
	private Integer montant;
	private Date datepaiement;

	public Facture() {
	}

	public Facture(int idfacture, Commande commande, Paiement paiement) {
		this.idfacture = idfacture;
		this.commande = commande;
		this.paiement = paiement;
	}

	public Facture(int idfacture, Commande commande, Paiement paiement, Integer montant, Date datepaiement) {
		this.idfacture = idfacture;
		this.commande = commande;
		this.paiement = paiement;
		this.montant = montant;
		this.datepaiement = datepaiement;
	}

	@Id

	@Column(name = "idfacture", unique = true, nullable = false)
	public int getIdfacture() {
		return this.idfacture;
	}

	public void setIdfacture(int idfacture) {
		this.idfacture = idfacture;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "numcommande", unique = true, nullable = false)
	@JsonIgnoreProperties("factures")
	public Commande getCommande() {
		return this.commande;
	}

	public void setCommande(Commande commande) {
		this.commande = commande;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_paiement", unique = true, nullable = false)
	@JsonIgnoreProperties("factures")
	public Paiement getPaiement() {
		return this.paiement;
	}

	public void setPaiement(Paiement paiement) {
		this.paiement = paiement;
	}

	@Column(name = "montant")
	public Integer getMontant() {
		return this.montant;
	}

	public void setMontant(Integer montant) {
		this.montant = montant;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datepaiement", length = 13)
	public Date getDatepaiement() {
		return this.datepaiement;
	}

	public void setDatepaiement(Date datepaiement) {
		this.datepaiement = datepaiement;
	}

}
