package org.sid.reverse;
// Generated 30 avr. 2019 01:04:31 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Lignedecommande generated by hbm2java
 */
@Entity
@Table(name = "lignedecommande", schema = "public", uniqueConstraints = { @UniqueConstraint(columnNames = "id_article"),
		@UniqueConstraint(columnNames = "numcommande"),
		@UniqueConstraint(columnNames = { "numcommande", "id_article" }) })
public class Lignedecommande implements java.io.Serializable {

	private int idlignedecommande;
	private Commande commande;
	private Article article;
	private Date datecommander;
	private Integer quantitecommander;

	public Lignedecommande() {
	}

	public Lignedecommande(int idlignedecommande, Commande commande, Article article) {
		this.idlignedecommande = idlignedecommande;
		this.commande = commande;
		this.article = article;
	}

	public Lignedecommande(int idlignedecommande, Commande commande, Article article, Date datecommander,
			Integer quantitecommander) {
		this.idlignedecommande = idlignedecommande;
		this.commande = commande;
		this.article = article;
		this.datecommander = datecommander;
		this.quantitecommander = quantitecommander;
	}

	@Id

	@Column(name = "idlignedecommande", unique = true, nullable = false)
	public int getIdlignedecommande() {
		return this.idlignedecommande;
	}

	public void setIdlignedecommande(int idlignedecommande) {
		this.idlignedecommande = idlignedecommande;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "numcommande", unique = true, nullable = false)
	@JsonIgnoreProperties("commandes")
	public Commande getCommande() {
		return this.commande;
	}

	public void setCommande(Commande commande) {
		this.commande = commande;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_article", unique = true, nullable = false)
	@JsonIgnoreProperties("commandes")
	public Article getArticle() {
		return this.article;
	}

	public void setArticle(Article article) {
		this.article = article;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datecommander", length = 13)
	public Date getDatecommander() {
		return this.datecommander;
	}

	public void setDatecommander(Date datecommander) {
		this.datecommander = datecommander;
	}

	@Column(name = "quantitecommander")
	public Integer getQuantitecommander() {
		return this.quantitecommander;
	}

	public void setQuantitecommander(Integer quantitecommander) {
		this.quantitecommander = quantitecommander;
	}

}
