package org.sid.reverse;
// Generated 30 avr. 2019 01:04:31 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Livraison generated by hbm2java
 */
@Entity
@Table(name = "livraison", schema = "public")
public class Livraison implements java.io.Serializable {

	private int idLivraison;
	private Date dateLivraison;
	private Set<Commande> commandes = new HashSet(0);

	public Livraison() {
	}

	public Livraison(int idLivraison) {
		this.idLivraison = idLivraison;
	}

	public Livraison(int idLivraison, Date dateLivraison, Set<Commande> commandes) {
		this.idLivraison = idLivraison;
		this.dateLivraison = dateLivraison;
		this.commandes = commandes;
	}

	@Id

	@Column(name = "id_livraison", unique = true, nullable = false)
	public int getIdLivraison() {
		return this.idLivraison;
	}

	public void setIdLivraison(int idLivraison) {
		this.idLivraison = idLivraison;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_livraison", length = 13)
	public Date getDateLivraison() {
		return this.dateLivraison;
	}

	public void setDateLivraison(Date dateLivraison) {
		this.dateLivraison = dateLivraison;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "livraison")
	@JsonIgnoreProperties("livraison")
	public Set<Commande> getCommandes() {
		return this.commandes;
	}

	public void setCommandes(Set<Commande> commandes) {
		this.commandes = commandes;
	}

}
