package org.sid.reverse;
// Generated 30 avr. 2019 01:04:31 by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Paiement generated by hbm2java
 */
@Entity
@Table(name = "paiement", schema = "public")
public class Paiement implements java.io.Serializable {

	private int idPaiement;
	private Set<Facture> factures = new HashSet(0);

	public Paiement() {
	}

	public Paiement(int idPaiement) {
		this.idPaiement = idPaiement;
	}

	public Paiement(int idPaiement, Set<Facture> factures) {
		this.idPaiement = idPaiement;
		this.factures = factures;
	}

	@Id

	@Column(name = "id_paiement", unique = true, nullable = false)
	public int getIdPaiement() {
		return this.idPaiement;
	}

	public void setIdPaiement(int idPaiement) {
		this.idPaiement = idPaiement;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "paiement")
	@JsonIgnoreProperties("paiement")
	public Set<Facture> getFactures() {
		return this.factures;
	}

	public void setFactures(Set<Facture> factures) {
		this.factures = factures;
	}

}
