package org.sid.reverse;
// Generated 30 avr. 2019 01:04:31 by Hibernate Tools 3.6.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role", schema = "public")
public class Role implements java.io.Serializable {

	private int idRole;
	private Utilisateur utilisateur;
	private String nomrole;

	public Role() {
	}

	public Role(int idRole, Utilisateur utilisateur) {
		this.idRole = idRole;
		this.utilisateur = utilisateur;
	}

	public Role(int idRole, Utilisateur utilisateur, String nomrole) {
		this.idRole = idRole;
		this.utilisateur = utilisateur;
		this.nomrole = nomrole;
	}

	@Id

	@Column(name = "id_role", unique = true, nullable = false)
	public int getIdRole() {
		return this.idRole;
	}

	public void setIdRole(int idRole) {
		this.idRole = idRole;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_utilisateur", nullable = false)
	@JsonIgnoreProperties("roles")
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	@Column(name = "nomrole", length = 254)
	public String getNomrole() {
		return this.nomrole;
	}

	public void setNomrole(String nomrole) {
		this.nomrole = nomrole;
	}

}
