package org.sid.reverse;
// Generated 30 avr. 2019 01:04:31 by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Sectionart generated by hbm2java
 */
@Entity
@Table(name = "sectionart", schema = "public")
public class Sectionart implements java.io.Serializable {

	private int idsection;
	private String nomsection;
	private Set<Article> articles = new HashSet(0);

	public Sectionart() {
	}

	public Sectionart(int idsection) {
		this.idsection = idsection;
	}

	public Sectionart(int idsection, String nomsection, Set<Article> articles) {
		this.idsection = idsection;
		this.nomsection = nomsection;
		this.articles = articles;
	}

	@Id

	@Column(name = "idsection", unique = true, nullable = false)
	public int getIdsection() {
		return this.idsection;
	}

	public void setIdsection(int idsection) {
		this.idsection = idsection;
	}

	@Column(name = "nomsection", length = 254)
	public String getNomsection() {
		return this.nomsection;
	}

	public void setNomsection(String nomsection) {
		this.nomsection = nomsection;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "sectionart")
	@JsonIgnoreProperties("sectionart")
	public Set<Article> getArticles() {
		return this.articles;
	}

	public void setArticles(Set<Article> articles) {
		this.articles = articles;
	}

}
