package org.sid.reverse;
// Generated 30 avr. 2019 01:04:31 by Hibernate Tools 3.6.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Superviseur generated by hbm2java
 */
@Entity
@Table(name = "superviseur", schema = "public")
public class Superviseur implements java.io.Serializable {

	private int idUtilisateur;
	private Utilisateur utilisateur;
	private Chambremetier chambremetier;
	private String superviseur;

	public Superviseur() {
	}

	public Superviseur(Utilisateur utilisateur, Chambremetier chambremetier, String superviseur) {
		this.utilisateur = utilisateur;
		this.chambremetier = chambremetier;
		this.superviseur = superviseur;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "utilisateur"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "id_utilisateur", unique = true, nullable = false)
	public int getIdUtilisateur() {
		return this.idUtilisateur;
	}

	public void setIdUtilisateur(int idUtilisateur) {
		this.idUtilisateur = idUtilisateur;
	}

	@OneToOne(fetch = FetchType.EAGER)
	@JsonIgnoreProperties("superviseur")
	@PrimaryKeyJoinColumn
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JsonIgnoreProperties("utilisateurs")
	@JoinColumn(name = "id_chambremetier", nullable = false)
	public Chambremetier getChambremetier() {
		return this.chambremetier;
	}

	public void setChambremetier(Chambremetier chambremetier) {
		this.chambremetier = chambremetier;
	}

	@Column(name = "superviseur", nullable = false, length = 254)
	public String getSuperviseur() {
		return this.superviseur;
	}

	public void setSuperviseur(String superviseur) {
		this.superviseur = superviseur;
	}

}
