package org.sid.reverse;
// Generated 30 avr. 2019 01:04:31 by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Villageartisanal generated by hbm2java
 */
@Entity
@Table(name = "villageartisanal", schema = "public")
public class Villageartisanal implements java.io.Serializable {

	private int idVillageartisanal;
	private Chambremetier chambremetier;
	private String nomVillageartisanal;
	private String communeVillageartisanal;
	private String adressvilageartisanal;
	//private Set<Artisan> artisans = new HashSet(0);

	public Villageartisanal() {
	}

	public Villageartisanal(int idVillageartisanal, Chambremetier chambremetier) {
		this.idVillageartisanal = idVillageartisanal;
		this.chambremetier = chambremetier;
	}

	public Villageartisanal(int idVillageartisanal, Chambremetier chambremetier, String nomVillageartisanal,
			String communeVillageartisanal, String adressvilageartisanal, Set<Artisan> artisans) {
		this.idVillageartisanal = idVillageartisanal;
		this.chambremetier = chambremetier;
		this.nomVillageartisanal = nomVillageartisanal;
		this.communeVillageartisanal = communeVillageartisanal;
		this.adressvilageartisanal = adressvilageartisanal;
		//this.artisans = artisans;
	}

	@Id

	@Column(name = "id_villageartisanal", unique = true, nullable = false)
	public int getIdVillageartisanal() {
		return this.idVillageartisanal;
	}

	public void setIdVillageartisanal(int idVillageartisanal) {
		this.idVillageartisanal = idVillageartisanal;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_chambremetier", nullable = false)
	@JsonIgnoreProperties("villageatisanals")
	public Chambremetier getChambremetier() {
		return this.chambremetier;
	}

	public void setChambremetier(Chambremetier chambremetier) {
		this.chambremetier = chambremetier;
	}

	@Column(name = "nom_villageartisanal", length = 254)
	public String getNomVillageartisanal() {
		return this.nomVillageartisanal;
	}

	public void setNomVillageartisanal(String nomVillageartisanal) {
		this.nomVillageartisanal = nomVillageartisanal;
	}

	@Column(name = "commune_villageartisanal", length = 254)
	public String getCommuneVillageartisanal() {
		return this.communeVillageartisanal;
	}

	public void setCommuneVillageartisanal(String communeVillageartisanal) {
		this.communeVillageartisanal = communeVillageartisanal;
	}

	@Column(name = "adressvilageartisanal", length = 254)
	public String getAdressvilageartisanal() {
		return this.adressvilageartisanal;
	}

	public void setAdressvilageartisanal(String adressvilageartisanal) {
		this.adressvilageartisanal = adressvilageartisanal;
	}
/*
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "villageartisanal")
	@JsonIgnoreProperties("villageartisanal")
	public Set<Artisan> getArtisans() {
		return this.artisans;
	}

	public void setArtisans(Set<Artisan> artisans) {
		this.artisans = artisans;
	}*/

}
